# Generated by Django 6.0 on 2025-12-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='office_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user_type',
        ),
    ]
