# Generated by Django 6.0 on 2025-12-16 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0002_remove_userinfo_office_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='portfolio_thumbnails/')),
                ('project_discriptions', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('date_finished', models.DateTimeField(null=True)),
                ('date_save', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_path', models.ImageField(blank=True, null=True, upload_to='portfolio_files/')),
                ('date_save', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_id', to='myPortfolioApp.portfolio_details')),
            ],
        ),
    ]
