# Generated by Django 6.0 on 2025-12-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0004_portfolio_features_portfolio_features_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_details',
            name='project_discriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio_features',
            name='feature_discriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
