# Generated by Django 6.0 on 2025-12-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0005_alter_portfolio_details_project_discriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_details',
            name='project_discriptions_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
