# Generated by Django 6.0 on 2025-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPortfolioApp', '0006_portfolio_details_project_discriptions_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_features',
            name='feature_discriptions_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
